--color=fg:#c8d3f5,bg:#1e2030,hl:#86e1fc
--color=fg+:#c8d3f5,bg+:#2f334d,hl+:#86e1fc
--color=border:#636da6,list-border:#636da6,input-border:#636da6,preview-border:#636da6
--color=gutter:#1e2030,info:#636da6,separator:#636da6,scrollbar:#636da6
--color=prompt:#82aaff,pointer:#c099ff,marker:#c099ff,spinner:#c099ff,query:#c8d3f5,header:#636da6
--color=list-label:#c099ff,input-label:#82aaff,preview-label:#c3e88d
