# --- cargo ---
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

# --- go ---
export PATH="$HOME/go/bin:$PATH"

# --- tuxedo ---
export TODO_DIR="$HOME/Documents/todo"
export TODO_FILE="$TODO_DIR/todo.txt"
export DONE_FILE="$TODO_DIR/done.txt"
