name: Lint Lua files

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4
      - name: Ensure luacheck installed
        run: command -v luacheck || (sudo apt-get update && sudo apt-get install -y lua-check)
      - run: just lint-lua
